---
- name: Install Tailscale Now
  hosts: all
  become: true
  tasks:
    - name: Download Tailscale GPG Key
      ansible.builtin.uri:
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg 

    - name: Add Tailscale repository
      ansible.builtin.uri:
        dest: /etc/apt/sources.list.d/tailscale.list
        url: https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list

    - name: Install Tailscale
      ansible.builtin.apt:
        name: tailscale
        update_cache: true
        state: present 

    - name: Join Tailscale
       ansible.builtin.shell:
         cmd: tailscale up --auth-key=tskey-auth-kavwaucvab11CNTRL-bGiMr5WQMwAVb6fM2mmxwAtzZ8hnmZ3Hf --hostname=$HOSTNAME

    - name: Install proxmox agent
      ansible.builtin.shell:
          cmd: apt-get install qemu-guest-agent -y && systemctl start qemu-guest-agent && systemctl enable qemu-guest-agent && shutdown now
