---
- hosts: all
  
  become: true
  become_user: root
  tasks:
     - name: Restarts custom bouncer and removes all decisions
       ansible.builtin.shell:
          cmd: systemctl restart crowdsec-custom-bouncer && cscli decisions delete --all
